## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from gm_config import gm_api

# Configure gmaps API key
gmaps.configure(api_key=gm_api)

In [2]:
# 1. Import the WeatherPy_database.csv file. 

city_weather_df = pd.read_csv("/Users/lisahanson/desktop/class/api/weather_database/WeatherPy_Database.csv")
city_weather_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Punta Arenas,CL,-53.1500,-70.9167,44.71,65,40,21.85,scattered clouds
1,1,Narsaq,GL,60.9167,-46.0500,14.22,69,82,10.00,broken clouds
2,2,Cidreira,BR,-30.1811,-50.2056,72.07,72,93,13.42,overcast clouds
3,3,Faanui,PF,-16.4833,-151.7500,81.34,76,80,14.20,light rain
4,4,Hilo,US,19.7297,-155.0900,72.81,88,35,4.29,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip?"))
max_temp = float(input("What is the maximum temperature you would like for your trip?"))

What is the minimum temperature you would like for your trip?75
What is the maximum temperature you would like for your trip?90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

preferred_cities_df = city_weather_df.loc[(city_weather_df["Max Temp"] <= max_temp) & \
                                          (city_weather_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
3,3,Faanui,PF,-16.4833,-151.7500,81.34,76,80,14.20,light rain
7,7,Vaini,TO,-21.2000,-175.2000,80.47,83,20,20.31,light rain
12,12,Gisborne,NZ,-38.6533,178.0042,80.22,68,20,3.44,few clouds
17,17,Kapaa,US,22.0752,-159.3190,76.98,74,75,4.61,broken clouds
20,20,Rikitea,PF,-23.1203,-134.9692,79.11,73,30,18.45,scattered clouds
23,23,Avarua,CK,-21.2078,-159.7750,80.65,83,40,11.50,scattered clouds
25,25,Broken Hill,AU,-31.9500,141.4333,85.03,30,10,15.73,clear sky
30,30,Butaritari,KI,3.0707,172.7902,81.72,78,100,14.50,light rain
44,44,Atuona,PF,-9.8000,-139.0333,78.78,76,10,17.25,clear sky
48,48,Kavaratti,IN,10.5669,72.6420,80.19,71,100,14.67,overcast clouds

In [12]:
# 4a. Determine if there are any empty rows.
#preferred_cities_df.count()

#isnull() Method
##preferred_cities_df.isnull()
##preferred_cities_df.isnull().sum()

#notnull() - returns true values
preferred_cities_df.notnull().sum()

City_ID                123
City                   123
Country                123
Lat                    123
Lng                    123
Max Temp               123
Humidity               123
Cloudiness             123
Wind Speed             123
Weather Description    123
dtype: int64

In [13]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Weather Description    0
dtype: int64

In [14]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

#Drop the row that has the missing value
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
3,3,Faanui,PF,-16.4833,-151.7500,81.34,76,80,14.20,light rain
7,7,Vaini,TO,-21.2000,-175.2000,80.47,83,20,20.31,light rain
12,12,Gisborne,NZ,-38.6533,178.0042,80.22,68,20,3.44,few clouds
17,17,Kapaa,US,22.0752,-159.3190,76.98,74,75,4.61,broken clouds
20,20,Rikitea,PF,-23.1203,-134.9692,79.11,73,30,18.45,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
544,544,Namuac,PH,18.6109,121.1657,80.29,72,15,13.40,few clouds
548,548,Paka,MY,4.6374,103.4368,78.73,94,40,5.75,scattered clouds
553,553,Santa Cruz Cabralia,BR,-16.2781,-39.0247,79.03,83,20,1.14,few clouds
556,556,Nhulunbuy,AU,-12.2333,136.7667,86.61,74,75,14.97,broken clouds
557,557,Kawalu,ID,-7.3817,108.2082,75.78,88,100,1.79,overcast clouds

In [20]:
clean_df = preferred_cities_df.dropna(axis = 0, how ='any')

In [23]:
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
3,3,Faanui,PF,-16.4833,-151.7500,81.34,76,80,14.20,light rain
7,7,Vaini,TO,-21.2000,-175.2000,80.47,83,20,20.31,light rain
12,12,Gisborne,NZ,-38.6533,178.0042,80.22,68,20,3.44,few clouds
17,17,Kapaa,US,22.0752,-159.3190,76.98,74,75,4.61,broken clouds
20,20,Rikitea,PF,-23.1203,-134.9692,79.11,73,30,18.45,scattered clouds
...,...,...,...,...,...,...,...,...,...,...
544,544,Namuac,PH,18.6109,121.1657,80.29,72,15,13.40,few clouds
548,548,Paka,MY,4.6374,103.4368,78.73,94,40,5.75,scattered clouds
553,553,Santa Cruz Cabralia,BR,-16.2781,-39.0247,79.03,83,20,1.14,few clouds
556,556,Nhulunbuy,AU,-12.2333,136.7667,86.61,74,75,14.97,broken clouds
557,557,Kawalu,ID,-7.3817,108.2082,75.78,88,100,1.79,overcast clouds

In [24]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

In [25]:
# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
3,Faanui,PF,81.34,light rain,-16.4833,-151.7500,
7,Vaini,TO,80.47,light rain,-21.2000,-175.2000,
12,Gisborne,NZ,80.22,few clouds,-38.6533,178.0042,
17,Kapaa,US,76.98,broken clouds,22.0752,-159.3190,
20,Rikitea,PF,79.11,scattered clouds,-23.1203,-134.9692,
23,Avarua,CK,80.65,scattered clouds,-21.2078,-159.7750,
25,Broken Hill,AU,85.03,clear sky,-31.9500,141.4333,
30,Butaritari,KI,81.72,light rain,3.0707,172.7902,
44,Atuona,PF,78.78,clear sky,-9.8000,-139.0333,
48,Kavaratti,IN,80.19,overcast clouds,10.5669,72.6420,

In [81]:
 #Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": gm_api,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
#len(hotels["results"])
hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEDZX5MnL7xCzp7_XBH5n_u0W4bN2kMEwhPUSH4o_nMt1SqXvS90ZOrIREI2LEmgAco0f2A1GA56SaBiLbAfMvG3hQpDOJrOWEtJNcNhX-kyesBtz5_Rm_uK7pkR9v3XnyZ0Zie9W8VdjyYksS4DyrjIBmqXJvBE6yYr8OiuC77I5S8BdYDNwoFHTCoK6QWxoaDRAqZ6tuIqhxHSu6r-FjfZmrFT54LAsSJVL-RLjgYVTSn17uZQeszJMRIcnrDpJR3Z7uCo6ezmeLXbGzkk_Xv8f8hhL6uEIHiUNEEZ8180i6K5tW4gDNzpsIjfzvxHycbJhLMXRNTJmcO_oXjqJ6QYnmtlBWPQinJt8GuAJk-7iAk0WfpG6GqEAegSSkNFKIuqJPgSLr6_Qkctb8mw8yaFegeHh0ngUYV4tvw7eu0WfeWVxMzSxXBE',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEBLswlzeNZlkoobRBdtSP63Jg6rUzkc9Mm5YymfRPo8Q6ovZERBKSVMW54Rp5vx2is3hV1EuU9OpdmQwGYzWtdDfqKwivAlIwKpkkLIN4segcJJ5jkfaRV06ihLAN18o3DFc9NLLkZwENXCcfU4IY53gdDMXg9OYQ07ykE5LhPWI077',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 317,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uECxIqlVDKxhi7qmlU1W-IXd2PyAE5YGBW08Bj1pMba3sJhTPaPvPodUlz4NLzy6FBe8MX4IVXdwFyxgqHNlKU-Qf75aEmCzVTRZk2eo5B0ECgkDvIKBUKkC5bNL_EadBpXadzF2nS7FIqBe21A_6eEN8S3ko7BIu3kxpVoGZo5_J-Gu',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 696,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEBP20_3nIK1JMAL7ktyp3-CR5FNzQVtmc9BFo2g_hDw-sG-n_JYPoxPo_fcAsoUTjwKgS7yPSFjvaBXCbXjhGbeVFTt6ucB5oto3Kdusf86tNvjkqNRBdXRsN1aEkP8QIEl897EnhBMRGaJeySOjyGEGPCHr9O6AgBUXNcpa73sE6fc',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 892,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEDYhJLxAz_v8CuisOyFNUeXZ6o12geKohJEZm7RPazAgJrDWMe8EA-Pmfm5_W6Gbr8fkDWrymENjA3CtOYJzjrfLYoBDp2DbLcfp7AQFxsV5FKig3EGR42OItNawjc-CktP7XvaABXBBkNXXhXsZtFYCvuMEk11s68uFjtUiv6CneUs',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2353,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uEBVstYOH_-1wb1ISST_6rU7q1fbL-aWH5eCVGVAbgY3n7oKpy-BHM-Um9fGtAc-_2eWYn_ZuKzBPNV0qGFnx6yiGgPlIX37gNf86fvhx4Gz-IStcn_pQCve9s6EUbzC6LAagkggb1SqDcKsQvPnwF1SWQHRmtJVVyNFDho0ne5HRww8',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 284,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEAZmdQPXeqYln7vuvcbgEJv_fy70fGbhJ5PJ8MX4_MZA9dkgrnfu2kK5CL_6t6t6xOtft62bvzJIPa1eXcZMkLbfBPnl3SrwGO84XkBDypGhKR0QVZDtHrO9oXiBQo3gfSE5l3gHVeEzu22oUO_rGZcJdLwrl2hRfitBGpFb0y36Oj5',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 726,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uEBQH8nX_Xg_keYLaGYhAxelv9NCCnjlSdQszRMJYyTIgQjUFcyOhQbvbwLEXUTh3wCsUhrXGc3rWOC7FamgQI_HJN4XAUFdQVRnNUjblD0vVDrE4W6RaN92ZyNv8oaO8xM3Z9Lh6NJNPcsdBpKayECUPFLSnT3sNFeQAzeE7g090eJy',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 403,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEAAeiCktpsDRvuVIhJK5BzNRz3v0YeWKjj2VryA93DEV5Z1WzbWpF5NA1F4vZrnVFUWicjBgBfKjk-X6FINMrDTtbyg5li8i4y0grYDGX8Rj_AJpQvIzC6TnjZ_lj-OzWTRcIJwisKqv_cDj_7k8cN706KjMmMrvQs1RUNklleCRyOX',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 511,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uECGd-QCB7eO1lN5palwIYBA_kwvq5drS8ekf2Rl8FE2zAQn6HOMk5UeZ7FLx7vabZgOfZzJTbjZT5bMgjMCTcUoJ7g_3DAbH75AiVP8Mto95BmPCCJRp3NE3ejwhHHlfOCybBwfNxv-Mat6LkBr3jLuasIygO_0ZJV_53HoPK6TEA8R',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 862,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEBhGb6gDm_QpWtbgY7l-k8cj8wcv9UP9NWLvPlIGOGzK57hYejxVXqTU0NDRKdOgcVtvDSBDYLt2s3tCGOgIYXzZAe_e7xKVmLM-fH7fDNCzGLgor6GNXhz-wDZa_3Ttaa5yC7u85Vfl0uYu9_woDieeLrV3hQDZoesFok3VyTl_MYN',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.2,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 202,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488820802915,
      'lng': 2.373123430291502},
     'southwest': {'lat': 48.8461841197085, 'lng': 2.370425469708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uECCdlaPfvmWASpP6V2dVyTIxgYcNZq6UNSr2h9vaS_SfoA6WBgQ-iAZrCA8cBWYQx_sCYNQXGSRxQmViP56Xm9aTPXCNVwJDpLLm3807vV1z9QKRFmqEpO-KFlOngdo9ikPkdw3Gb4iuLLQC0IQjDmO5QhA2ohI9sYukwvqMcCk8X0N',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 383,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106224131803115407650">Marcin Marczak</a>'],
     'photo_reference': 'Aap_uEBm_qOX4FYJ5lvcq1mr1OlW4FWJZFShpTcnZgZpJvDO4Mhwx_ZT5cpJnUpAcJy6fNCioL_dDD2KV3v47o4ZYMUiDLGRvyDFe9seHI2f9RWxEi0SAXL_069OVZyjtlOZ5aUoWZ0D_8fG23gOIOXudukioZ2dhNmMNz9NPa5sgR6kOn1J',
     'width': 3264}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 415,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uEB1OcvA_js5nVbP3QtRJWj_XSNI7BWyXiXtCsbuFI_9jafjrhwUtVOdo-ZCxctDPihSb1fCHSLVp7BKHYAxE0GmcBihJzmvOyEuNHhY7wSE9_TfZ6bRZ-c36HyrLrtdYmAD8kjOk1lyBHwpOIaEj9lvtoJHPq71F5Cmanc6j87EX-lj',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 465,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'permanently_closed': True,
   'photos': [{'height': 650,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEDpEe-VEwp6KiyQiWUC-MvZtE93ekYJhxdYM_adK1l8cAMsl1Rpzl5yJOv7Z3VuRhWkJ5rTZ6qSRe0EoYB8LVXO76bDcQSmQTsfT7Uqf_lqcuNEGm2noQcISL4gK-Ekmr6s96bxtq4Q34hjoIxVJIthhziRJNvx4m9n0deZ32a5cOPL',
     'width': 802}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1074,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724169302915,
      'lng': 2.340369280291502},
     'southwest': {'lat': 48.8697189697085, 'lng': 2.337671319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [56]:
# 6a. Set parameters to search for hotels with 5000 meters.

params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": gm_api
}

In [82]:
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
     # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    
    except (IndexError):
        print("Hotel not found ... skipping.")

Hotel not found ... skipping.
Hotel not found ... skipping.

In [83]:
hotel_df

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
3,Faanui,PF,81.34,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
7,Vaini,TO,80.47,light rain,-21.2000,-175.2000,Keleti Beach Resort
12,Gisborne,NZ,80.22,few clouds,-38.6533,178.0042,ASURE Alfresco Motor Lodge
17,Kapaa,US,76.98,broken clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
20,Rikitea,PF,79.11,scattered clouds,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...
544,Namuac,PH,80.29,few clouds,18.6109,121.1657,Mlin Hotel
548,Paka,MY,78.73,scattered clouds,4.6374,103.4368,RUMBIA RESORT VILLA Paka Terengganu
553,Santa Cruz Cabralia,BR,79.03,few clouds,-16.2781,-39.0247,Puerto Princesa Inn
556,Nhulunbuy,AU,86.61,broken clouds,-12.2333,136.7667,East Arnhem Real Estate
557,Kawalu,ID,75.78,overcast clouds,-7.3817,108.2082,KOSAN UNGU UNSIK

In [84]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(axis = 0, how ='any')

In [85]:
# 8a. Create the output File (CSV)
output_data_file = "/Users/lisahanson/desktop/class/api/vacation_search/WeatherPy_vacation.csv"


# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [73]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.


info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [74]:
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]



# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [75]:
# 11a. Add a marker layer for each city to the map. 

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 11b. Display the figure

fig.add_layer(marker_layer)

In [76]:
fig

Figure(layout=FigureLayout(height='420px'))